### ISSUE TITLE
The difference between typescript and Lua of implicit conversion Boolean

### ISSUE THREAD

**Issue by AserJoker** [TypeScriptToLua/TypeScriptToLua#1243] opened 2022-03-30 02:04 UTC
When I wanted to know that a variable was literally empty, I encountered a strange bug.After investigation, it is found that it is caused by different language characteristics.
when I write code like:
```typescript
const a = SomeFunction();
if(a){
    Do Some Thing;
}
```
I means a is a not literally empty, not null,not false,not zero,not empty string .etc
but
```lua
if(a) then
 Do Some Thing;
end
```
meas a is not nil.
This may have an unknown consequence
maybe  “if(expr)” can transform to "if(a~=nil and a ~= 0 and a ~='' and a ~= false)"?

**Comment by AserJoker** [comment] 2022-03-30 02:06
The same applies to "if(!a)"

**Comment by Zamiell** [comment] 2022-03-30 02:09
As a general rule of thumb, it's not a good idea / best practice to use the "loose equality" features of JavaScript, TypeScript, or Lua. If you do not use these features, the the issue vanishes.

See: https://github.com/TypeScriptToLua/TypeScriptToLua/issues/1212#issuecomment-1026077897, which is a similar issue.

**Comment by AserJoker** [comment] 2022-04-01 04:29
@Zamiell  you are right . However, this is not conducive to the migration of existing projects. Maybe a TS transformer can be provided to solve this problem. Sometimes, it is not a good idea to modify the source code through eslint

**Comment by Perryvw** [comment] 2022-04-02 12:12
Intentional tstl behaviour, closing this as duplicate of #1212

**Closed by Perryvw** 2022-04-02 12:12 UTC
