### ISSUE TITLE
Bug when destructuring a result directly.

### ISSUE THREAD

**Issue by yancouto** [TypeScriptToLua/TypeScriptToLua#995] opened 2021-02-28 22:25 UTC
I reproduce this bug using `string.find`, but maybe it applies to all `@tupleReturn`?

The following code reproduces this error on the tstl playground:
```
// works as it should
const result = string.find("a", "b");
const [c, ...d] = result;

// Doesn't work
const [a, ...b] = string.find("a", "b");
```

Gets translated to
```
result = {
    string.find("a", "b")
}
c = result[1]
d = __TS__ArraySlice(result, 1)
local ____ = string.find("a", "b")
a = ____[1]
b = __TS__ArraySlice(____, 1)
```

On the second case, it uses `string.find` result directly without putting it into a table, which causes a nil error.

**Comment by Perryvw** [comment] 2021-03-04 20:46
[Playground link](https://typescripttolua.github.io/play/#code/PTAEHcHsCcGsGdQENEEsAup4AtIFcAbAEwCgBjSAO3k2gFN5DMBeLdaVSgcwDoAzTkQAUAIiQiANKBEAjEQEoA3OSo1QAbTJSeOogF1QreowLplJEKAAikBpQDkmKHBXVM6pNp0yDrGh25+QVFxKVkFRSA)

Thanks for the bug report, this indeed a tricky issue.

Problematic code is this:
```ts
const [a, ...b] = string.find("a", "b");
```
We first assign the `string.find` result to a temporary variable because Lua cannot capture rest arguments like `...b`. The problem is that if string.find cannot find the match, the temporary variable is `nil` and indexing fails.

If this is changed to
```ts
const [a, b] = string.find("a", "b");
```
This is not an issue because it translates to `a, b = string.find("a", "b")`

Actually Lua does not support binding a rest value either (as far as I know), maybe we should just disallow destructuring with rest in MultiReturn values?

**Comment by yancouto** [comment] 2021-03-04 21:28
Since
```js
const result = string.find("a", "b");
const [a, ...b] = result;
```
works, I don't see the need to disallow, we just have to use the same logic on both.
The error is that `string.find("a", "b")` is assigned to `___`  without wrapping it in a table.

**Comment by Perryvw** [comment] 2021-03-04 21:32
Aaah I see, you are right. In case we destruct a LuaMultiReturn value and need to assign it to a temporary variable, this should wrap it in a table.

**Comment by yancouto** [comment] 2021-03-04 22:34
Took the liberty of submitting a PR for it (#997), would appreciate a review, I don't know the codebase.

**Closed** 2021-03-06 17:19 UTC
Labels: bug
