### ISSUE TITLE
Since 1.4.2 plugins seems to be ignored from Transpiler.emit 

### ISSUE THREAD

**Issue by weiqj** [TypeScriptToLua/TypeScriptToLua#1286] opened 2022-06-10 18:22 UTC
I tried to specify my own visitor as a plugin in EmitOptions. It worked before but no longer working after 1.4.2.

Is there a way that I can specify a custom visitor after 1.4.2?

Thanks

**Comment by weiqj** [comment] 2022-06-10 18:51
In transpiler.ts, from line 32 to line 40, the "plugins" from emitOptions is intentionally removed.

I honestly can't see any reason why?

**Comment by Perryvw** [comment] 2022-06-11 10:39
We moved the place plugins are loaded to a higher level, but that shouldn't really matter if you are just using our API which remained the same. Our tests https://github.com/TypeScriptToLua/TypeScriptToLua/blob/master/test/transpile/plugins/plugins.spec.ts still work fine with plugins and custom visitors.

Our lualib is also built using a visitor plugin specified via tsconfig which seems to work fine: https://github.com/TypeScriptToLua/TypeScriptToLua/blob/master/src/lualib/tsconfig.json

How are you calling tstl that is now no longer working?

**Comment by weiqj** [comment] 2022-06-11 12:07
@Perryvw,
Please bear with me because I am not very good at TypeScript. I am building a web frontend using TSTL. If my understanding is correct, the new plugin design will have to go through plugins.getPlugins, which will call transpilation.utils.resolvePlugin, which will call resolve.sync.

People will have difficulties getting it to work on a web application. I would suggest allowing the old plugin array from the emitOptions.

Also, I am trying to build from a local npm link and webpack. It can build but will fail when loading webworker. I will appreciate it if you can point me to what might go wrong.

Thanks a lot
Q

**Comment by Perryvw** [comment] 2022-06-11 12:33
I still don't know how you are calling tstl, as far as I can see EmitOptions in transpiler.ts still all accept plugins, even though _really_ we don't officially support calling these inner functions directly.

I would need to see your code to determine what the problem is.

You might also want to look at our website which is using webpack and also stubs some files in the webpack config: https://github.com/TypeScriptToLua/TypeScriptToLua.github.io/blob/source/docusaurus-plugin.js#L29

**Comment by weiqj** [comment] 2022-06-11 12:54
My code works fine until 1.4.1. It is something like below:

I believe in your transpiler.ts, between line 37 and 40, the external plugins replaced the internal ones in emitOptions.

As for stubs, I basically copied your config. If I use the official version the build is working fine. However if I compile with local npm link, the resulted code will not load with webloader. I am banging my head now.
`
transpiler.emit({
      program,
      sourceFiles: [sourceFile],
      writeFile(
        fileName: string,
        data: string,
        _writeBOM: any,
        _onError: any,
        sourceFiles = []
      ) {
          // Process write code
      },
      plugins: [
        {
          visitors: {
             // Vistor map
          }
         }
      ]
`

**Comment by Perryvw** [comment] 2022-06-11 13:05
Aha I see, before the plugins from EmitOptions would be merged with the ones resolved from the configuration, but seems that during the change the emitOption plugins were ignored unintentionally, that seems to be a bug.

**Closed** 2022-06-11 18:07 UTC
Labels: bug, scope: transpile
