### ISSUE TITLE
Tuple/ Array bug

### ISSUE THREAD

**Issue by zaoqi-unsafe** [TypeScriptToLua/TypeScriptToLua#544] opened 2019-05-01 09:54 UTC
https://gitlab.com/the-language/the-language/blob/cb8acab436254a0945828206ea6c085506af2992/core/pure/typescript/lang.ts#L223

https://gitlab.com/the-language/the-language/blob/cb8acab436254a0945828206ea6c085506af2992/core/pure/lua/lang.lua#L182

**Comment by zaoqi-unsafe** [comment] 2019-05-01 09:54
needs `+1`

**Comment by ark120202** [comment] 2019-05-01 23:48
Duplicate of #489

**Closed** 2019-05-02 05:59 UTC
