### ISSUE TITLE
Extending declared class results in "attempting to index a nil value"

### ISSUE THREAD

**Issue by lolleko** [TypeScriptToLua/TypeScriptToLua#493] opened 2019-03-24 09:57 UTC
```ts
declare class Test {};

class TestChild extends Test {
    
}
```

```lua
TestChild = TestChild or {};
TestChild.__index = TestChild;
TestChild.prototype = TestChild.prototype or {};
TestChild.prototype.__index = TestChild.prototype;
TestChild.prototype.constructor = TestChild;
TestChild.____super = Test;
setmetatable(TestChild, TestChild.____super);

-- Test ist nil therefor TestChild.____super is nil too
-- So TestChild.____super.prototype tries to index nil
setmetatable(TestChild.prototype, TestChild.____super.prototype);

TestChild.new = function(...)
    local self = setmetatable({}, TestChild.prototype);
    self:____constructor(...);
    return self;
end;
```

https://typescripttolua.github.io/play.html#src=declare%20class%20Test%20%7B%7D%3B%0A%0Aclass%20TestChild%20extends%20Test%20%7B%0A%20%20%20%20%0A%7D

**Comment by ark120202** [comment] 2019-03-24 10:07
That looks like an expected behavior to me. `declare` modifier just means that the following declaration should already exist at the runtime.

Considering that there is no way for normal lua to declare TSTL-compatible classes I don't see any real usage for `declare class`. The only place where it would appear would be compiled libraries, where it should work fine.

**Comment by tomblind** [comment] 2019-03-24 13:14
Yeah, even if we added the check, the class wouldn't work at all as expected. We could provide some kind of alternate behavior if `prototype` doesn't exist, but I'm not totally sure what would be the best thing to do in that case.

**Comment by Perryvw** [comment] 2019-05-26 15:46
Closing this for now as it seems intended behavior.

**Closed by Perryvw** 2019-05-26 15:46 UTC
Labels: bug
