### ISSUE TITLE
tsconfig.json not support extends?

### ISSUE THREAD

**Issue by takegine** [TypeScriptToLua/TypeScriptToLua#1434] opened 2023-04-28 03:41 UTC
base.json
```json
{
    "compilerOptions": {
        "types": ["@moddota/dota-lua-types"],
        "suppressImplicitAnyIndexErrors": true,
        "strictNullChecks": false,
        "strictPropertyInitialization": false
    },
    "tstl": {
        "luaTarget": "JIT",
        "sourceMapTraceback": true
    }
}
```
src/tsconfig.json
```json
{
    "extends": "../base.json",
    "include": [
        "../vscripts",
        "../shared",
    ]
}
```

when i run `tstl -p src --outDir dist`, the configOption `luaTarget` & `sourceMapTraceback` in `../base.json` which extends by `src/tsconfig.json` is no working.

**Comment by lolleko** [comment] 2023-04-28 08:29
Duplicate of #1415

**Closed** 2023-04-28 08:29 UTC
