### ISSUE TITLE
Iterating over arrays doesn't run as expected in typescript

### ISSUE THREAD

**Issue by XavierCHN** [TypeScriptToLua/TypeScriptToLua#1522] opened 2023-12-08 07:46 UTC
The typescript code:

```Typescript
const a: number[] = [1, 2, null, 4, 5];
for (let i of a) console.log(i)
```

will output:

```
1
2
null
4
5
```

The code will be transpiled to 

```Lua
local a = {
    1,
    2,
    nil,
    4,
    5
}
for ____, i in ipairs(a) do
    print(i)
end
```

which will print

```
1
2
```

**Comment by Zamiell** [comment] 2023-12-08 12:58
duplicate of #1216

**Comment by Zamiell** [comment] 2023-12-08 12:59
Also, the example in the OP doesn't even compile, a better example is this:
```ts
const a: Array<number | null> = [];
a.push(1, 2, null, 3, 4, 5);
for (let i of a) console.log(i)
```

**Closed** 2023-12-08 14:10 UTC
