### ISSUE TITLE
Declaration files  should not generate import statements

### ISSUE THREAD

**Issue by Perryvw** [TypeScriptToLua/TypeScriptToLua#494] opened 2019-03-24 10:24 UTC
Declaration files will not be transpiled, but imports from them will still create a `require(declaration)`, which causes a lua error due to the file not existing.

Ideally we also find a way to not import declared types and interfaces from non-declarations files.

**Comment by ark120202** [comment] 2019-03-24 10:31
Declaration files only affect type-checking in typescript. They just tell typescript that it's content exists at the runtime and don't affect generated code, so I don't think they should have different meaning in TSTL.

> which causes a lua error due to the file not existing

Declaration files may declare a Lua module, or do you mean declaration files that contain only types?

> Ideally we also find a way to not import declared types and interfaces from non-declarations files.

Duplicate of #178?

**Closed** 2019-05-22 08:23 UTC
Labels: enhancement
