### ISSUE TITLE
Runtime crash if a class extends Error

### ISSUE THREAD

**Issue by thatcosmonaut** [TypeScriptToLua/TypeScriptToLua#533] opened 2019-04-24 20:50 UTC
If you define a class that extends Error and then construct it at runtime, Lua crashes with

```attempt to index field '____super' (a nil value)```

**Comment by ark120202** [comment] 2019-04-24 20:54
Since Error class isn't implemented it's expected behavior.
For runtime it's the same as `class Foo extends undefined {}`

**Comment by ark120202** [comment] 2019-11-24 20:59
Resolved in #724.

**Closed by ark120202** 2019-11-24 20:59 UTC
