### ISSUE TITLE
When using watch mode, there is a problem compiling all files if there are changes from the second time.

### ISSUE THREAD

**Issue by nkari82** [TypeScriptToLua/TypeScriptToLua#1574] opened 2024-08-26 04:40 UTC
my tsconfig.json

```
{
  "compilerOptions": {
    "target": "esnext",
    "lib": [
      "esnext"
    ],
    "module": "commonjs",
    "types": [
      "@typescript-to-lua/language-extensions",
      "lua-types/jit",
      "projectdl"
    ],
    "strict": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "typeRoots": [
      "./types", "./node_modules"
    ],
    "rootDir": "ts",
    "outDir": "lua",
    "moduleResolution": "node",
    "resolveJsonModule": true
  },
  "tstl": {
    "luaTarget": "JIT",
    "noHeader": true,
    "luaLibImport": "require-minimal",
    "noImplicitSelf": true
  }
}
```

**Comment by Perryvw** [comment] 2024-08-29 19:50
Seems like a duplicate of #1575? I am expecting a `Expected to happen:` and `Actual outcome:` in this bug report with some reproduction example. This is impossible to investigate or reproduce like this.

**Closed by Perryvw** 2024-08-29 19:50 UTC
