### ISSUE TITLE
Decorators

### ISSUE THREAD

**Issue by librehome** [TypeScriptToLua/TypeScriptToLua#955] opened 2020-12-25 00:54 UTC
I propose some additional decorators. For example:

@LuaLocal - marks the typescript object instance local, which is not available in typescript.

Also I am thinking about some extra decorators that may improve compatibility, especially for arrays.

**Comment by lolleko** [comment] 2021-01-29 18:58
We are currently in the process of removing decorators/annotations in favour of language extensions (see #821, #969) wherever possible. So we probably won't add new ones unless absolutely necessary.
You might be able to add a custom decorator it yourself via a plugin.
If that is not possible or if you think others would benefit from the annotation please open a proposal detailing functionality and use cases of the annotation.

Anyway closing this since more information is needed and it is not really clear what the issue is.

**Closed by lolleko** 2021-01-29 18:58 UTC
Labels: more information needed
