### ISSUE TITLE
PrivateIdentifier is not supported?

### ISSUE THREAD

**Issue by takegine** [TypeScriptToLua/TypeScriptToLua#1261] opened 2022-04-18 06:55 UTC
do you want to support this?
```typescript
class A {
    #tick: number = 0
}
```

**Comment by lolleko** [comment] 2022-04-18 22:48
Duplicate of #925 

TL;DR difficult to implement for us, because we have to emulate "hard privacy" at runtime in Lua efficiently.

**Closed by lolleko** 2022-04-18 22:48 UTC
